version: "3.7"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # TCP интерфейс
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=secret123
    volumes:  
      - ./init-scripts:/docker-entrypoint-initdb.d  # Для создания таблицы при старте
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    restart: unless-stopped

  event_generator:
    build: ./event_generator
    container_name: event_generator
    volumes:
      - python_logs:/app  # Файл /app/events.out будет доступен через volume
    depends_on:
      - kafka
    restart: unless-stopped

  
  vector_clickhouse:
    image: timberio/vector:latest-alpine
    container_name: vector_clickhouse
    depends_on:
      - kafka
      - clickhouse
    volumes:
      - ./vector/vector_clickhouse.yaml:/etc/vector/vector.yaml:ro
    restart: unless-stopped

  vector_kafka:
    image: timberio/vector:latest-alpine
    container_name: vector_kafka
    depends_on:
      - kafka
    volumes:
      # Монтируем volume, где лежит файл с логами, в папку, указанную в конфигурации Vector
      - python_logs:/var/log/python_events
      - ./vector/vector_kafka.yaml:/etc/vector/vector.yaml:ro
    restart: unless-stopped
volumes:
    python_logs: