version: "3.7"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # TCP интерфейс
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./init-scripts:/docker-entrypoint-initdb.d  # Для создания таблицы при старте
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=no
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: unless-stopped

  vector:
    image: timberio/vector:latest
    container_name: vector
    depends_on:
      - kafka
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
      # важный момент: нужно подключить volume, где лежат логи auditd
      - ./auditd_logs/:/auditd_logs
    restart: unless-stopped

  auditd_demo:
    build: ./auditd_demo
    container_name: auditd_demo
    privileged: true
    volumes:
      - ./auditd_logs/:/var/log/audit
    environment:
      - container=docker
    restart: unless-stopped

