apiVersion: 1
datasources:
  - name: "ClickHouse"
    type: "vertamedia-clickhouse-datasource"
    access: proxy
    url: "http://clickhouse-cluster:8123"
    basicAuth: true
    basicAuthUser: "default"
    basicAuthPassword: "secret123"
    jsonData:
      defaultDatabase: "logs" 
      timeout: 30               
    secureJsonData:
      basicAuthPassword: "secret123" # Пароль для базовой аутентификации