{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ошибки по приложениям",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "logs",
     "dateTimeColDataType": "event_timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  application,\n  error_code,\n  count(*) as errors\nFROM logs.analytic_events_security_dist\nWHERE $timeFilter AND error_code != ''\nGROUP BY application, error_code\nORDER BY errors DESC",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT\n  application,\n  error_code,\n  count(*) as errors\nFROM logs.analytic_events_security_dist\nWHERE event_timestamp >= toDateTime(1740389371) AND event_timestamp <= toDateTime(1740410971) AND error_code != ''\nGROUP BY application, error_code\nORDER BY errors DESC",
     "round": "0s",
     "table": "analytic_events_security_dist"
    }
   ]
  },
  {
   "title": "Анализ типов событий",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "logs",
     "dateTimeColDataType": "event_timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  event_type,\n  count(*) as count\nFROM logs.analytic_events_security_dist\nWHERE $timeFilter\nGROUP BY event_type\nORDER BY count DESC",
     "rawQuery": "SELECT\n  event_type,\n  count(*) as count\nFROM logs.analytic_events_security_dist\nWHERE event_timestamp >= toDateTime(1740389371) AND event_timestamp <= toDateTime(1740410971)\nGROUP BY event_type\nORDER BY count DESC",
     "round": "0s",
     "table": "analytic_events_security_dist"
    }
   ]
  },
  {
   "title": "Временной ряд событий",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "logs",
     "dateTimeColDataType": "event_timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT (intDiv(toUInt32(event_timestamp), 20) * 20) * 1000 as t, count() FROM logs.analytic_events_security_dist WHERE event_timestamp >= toDateTime(1740389371) AND event_timestamp <= toDateTime(1740410971) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "analytic_events_security_dist"
    }
   ]
  },
  {
   "title": "Распределение логов по уровням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "logs",
     "dateTimeColDataType": "event_timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  log_level,\n  count(*) as count\nFROM logs.analytic_events_security_dist\nWHERE $timeFilter\nGROUP BY log_level",
     "rawQuery": "/* grafana dashboard=New dashboard, user=1 */\nSELECT\n  log_level,\n  count(*) as count\nFROM logs.\nWHERE event_timestamp >= toDateTime(1740389371) AND event_timestamp <= toDateTime(1740410971)\nGROUP BY log_level",
     "round": "0s",
     "table": "analytic_events_security_dist"
    }
   ]
  },
  {
   "title": "Детализированная таблица логов",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "contextWindowSize": "10",
     "database": "logs",
     "dateTimeColDataType": "event_timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  event_timestamp,\n  server,\n  application,\n  user,\n  source_ip,\n  destination_ip,\n  details,\n  status,\n  error_code,\n  raw_string\nFROM logs.analytic_events_security_dist\nWHERE $timeFilter\nORDER BY event_timestamp DESC\nLIMIT 100",
     "rawQuery": "SELECT\n  event_timestamp,\n  server,\n  application,\n  user,\n  source_ip,\n  destination_ip,\n  details,\n  status,\n  error_code,\n  raw_string\nFROM logs.analytic_events_security_dist\nWHERE event_timestamp >= toDateTime(1740389371) AND event_timestamp <= toDateTime(1740410971)\nORDER BY event_timestamp DESC\nLIMIT 100",
     "round": "0s",
     "table": "analytic_events_security_dist"
    }
   ]
  }
 ]
}